### ISSUE TITLE
0.5.1 version with django 1.9 compat fix problem

### ISSUE THREAD

**Issue by vint21h** [idlesign/django-sitemetrics#12]
Hello, you forgot upload new code to PyPI.

**Comment by idlesign** [comment]
Hi,

Actually I'm not, there is an unresolved minor tests suite issue if I'm not mistaken. 
Planning to address it in two days.

**Comment by idlesign** [comment]
0.5.2 is on PyPI now https://pypi.python.org/pypi/django-sitemetrics/0.5.2

**Comment by vint21h** [comment]
Thanks!
