### ISSUE TITLE
Error using caching in Django 1.11 with django-sitemetrics

### ISSUE THREAD

**Issue by mikesdnielsen** [idlesign/django-sitemetrics#16]
After having upgraded a Django 1.8 site to 1.11 (for LTS), when I enable caching in production I get the follow error: 

`File "/var/www/.../env/lib/python3.4/site-packages/sitemetrics/templatetags/sitemetrics.py", line 50, in sitemetrics
    cached = cache.get('sitemetrics')
  File "/var/www/.../env/lib/python3.4/site-packages/django/core/cache/backends/memcached.py", line 79, in get
    val = self._cache.get(key)
AttributeError: Can't get attribute 'ValuesQuerySet' on <module 'django.db.models.query' from '/var/www/.../env/lib/python3.4/site-packages/django/db/models/query.py'>`

Is there any way this can be solved?

**Comment by idlesign** [comment]
Thank you for the report.

Sure, I should try to address it in a couple of days. 
* Is it on sitemetrics 0.7?
* What caching backend is used?

**Comment by mikesdnielsen** [comment]
Yes, I'm on the most recent version 0.7.0 from pypi. 

The backend is Memcached through pylibmc (1.5.2)

```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyLibMCCache',
        'LOCATION': '127.0.0.1:11211',
        'KEY_PREFIX': 'secret',
        'BINARY': True,
        'OPTIONS': {
            'tcp_nodelay': True,
            'dead_timeout': 60,
            'ketama': True,
        },
    },
}
```

Thanks for the really quick reply :-)

**Comment by mikesdnielsen** [comment]
I think I might have "solved" this - could it be that it some how cached with ValuesQuerySet from a previous version of sitemetrics or pylibmc? At least, after restarting my memcached server it seems to have disappeared for now.

**Comment by idlesign** [comment]
That may be.
No problem. Feel free to reopen if required.
