### ISSUE TITLE
Support for Universal Analytics (analytics.js)

### ISSUE THREAD

**Issue by littlepea** [idlesign/django-sitemetrics#5]
There's a new SDK for Google Analytics which will soon replace the current ga.js:
https://developers.google.com/analytics/devguides/collection/analyticsjs/

    The analytics.js snippet is part of Universal Analytics, which is currently in public beta. 
    New users should use analytics.js. Existing ga.js users should create a new web property for analytics.js and dual tag their site. 
    It is perfectly safe to include both ga.js and analytics.js snippets on the same page.

**Comment by idlesign** [comment]
Implemented in #6.
Closing this.
