### ISSUE TITLE
`manage.py migrate` failure with django 1.8

### ISSUE THREAD

**Issue by pacahon** [idlesign/django-sitemetrics#7]
Traceback:
```
Synchronizing apps without migrations:
  Creating tables...
    Creating table thumbnail_kvstore
    Creating table sitemetrics_keycode
    Running deferred SQL...
Traceback (most recent call last):
...
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "django_site" does not exist
```
Hello. I'm trying to migrate from Django 1.7->1.8 and have a problem with sitemetrics module.
The problem is described here:
https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies
> Be aware, however, that unmigrated apps cannot depend on migrated apps

I have contrib.sites in INSTALLED_APPS and sites is migrated app. Maybe initial migrations should be included in module due to optional dependency from django.contrib.sites? (It solved my problem)

**Comment by idlesign** [comment]
Hi,

Thank you for this reminder, this issue will be solved in next release.
